/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paint;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author hlong
 */
public class PaintTool2 extends javax.swing.JPanel implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public static enum DrawMode{LINE,RECTANGLE,OVAL,PENCIL,ERASER,CURVE,TRIANGLE,BUCKET,PICKER,TEXT,SELECT}
    private DrawMode drawMode = DrawMode.PENCIL;
    
    /**
     * Tao form PaintTool
     */
    public PaintTool2() {
        initComponents();
       
    }

    public Image getImageIcon(String path){
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource(path));
        return image;
    }
    public DrawMode getDrawMode(){
        return drawMode;
    }
    public void setDrawMode(DrawMode newDrawMode){
        DrawMode oldDrawMode = this.drawMode;
        this.drawMode = newDrawMode;
        this.firePropertyChange("tool change", oldDrawMode, newDrawMode);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bCurve = new javax.swing.JToggleButton();
        bPicker = new javax.swing.JToggleButton();
        bPencil = new javax.swing.JToggleButton();
        bBucket = new javax.swing.JToggleButton();
        bFont = new javax.swing.JToggleButton();
        bLine = new javax.swing.JToggleButton();
        bRectangle = new javax.swing.JToggleButton();
        bOval = new javax.swing.JToggleButton();
        bEraser = new javax.swing.JToggleButton();
        bTriangle = new javax.swing.JToggleButton();
        select = new javax.swing.JToggleButton();



        bPicker.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bPicker);
        bPicker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/picker.png"))); // NOI18N
        bPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPickerActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(233, 247, 247));

        bPencil.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bPencil);
        bPencil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/pencil.png"))); // NOI18N
        bPencil.setSelected(true);
        bPencil.setPreferredSize(new java.awt.Dimension(40, 40));
        bPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPencilActionPerformed(evt);
            }
        });

        bBucket.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bBucket);
        bBucket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/bucket.png"))); // NOI18N
        bBucket.setPreferredSize(new java.awt.Dimension(40, 40));
        bBucket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBucketActionPerformed(evt);
            }
        });

        bFont.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bFont);
        bFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/font.png"))); // NOI18N
        bFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFontActionPerformed(evt);
            }
        });

        bLine.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bLine);
        bLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/line.png"))); // NOI18N
        bLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLineActionPerformed(evt);
            }
        });

        bRectangle.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bRectangle);
        bRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/rectangle.png"))); // NOI18N
        bRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRectangleActionPerformed(evt);
            }
        });

        bOval.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bOval);
        bOval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/oval.png"))); // NOI18N
        bOval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOvalActionPerformed(evt);
            }
        });

        bEraser.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bEraser);
        bEraser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/eraser.png"))); // NOI18N
        bEraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEraserActionPerformed(evt);
            }
        });


        bTriangle.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bTriangle);
        bTriangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/triangle.png"))); // NOI18N
        bTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTriangleActionPerformed(evt);
            }
        });

        buttonGroup1.add(select);
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
          bCurve.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(bCurve);
        bCurve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/curve.png"))); // NOI18N
        bCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCurveActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bEraser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bPencil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(bFont, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(bLine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOval, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(select, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bPencil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bFont, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bLine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bEraser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bOval, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void bOvalActionPerformed(java.awt.event.ActionEvent evt) {                                      
        setDrawMode(DrawMode.OVAL);
    }                                     

    private void bFontActionPerformed(java.awt.event.ActionEvent evt) {                                      
        setDrawMode(DrawMode.TEXT);
    }                                     

    private void bCurveActionPerformed(java.awt.event.ActionEvent evt) {                                       
        setDrawMode(DrawMode.CURVE);
    }                                      

    private void bPencilActionPerformed(java.awt.event.ActionEvent evt) {                                        
        setDrawMode(DrawMode.PENCIL);
    }                                       

    private void bLineActionPerformed(java.awt.event.ActionEvent evt) {                                      
        setDrawMode(DrawMode.LINE);
    }                                     

    private void bRectangleActionPerformed(java.awt.event.ActionEvent evt) {                                      
        setDrawMode(DrawMode.RECTANGLE);
    }                                     

    private void bBucketActionPerformed(java.awt.event.ActionEvent evt) {                                        
        setDrawMode(DrawMode.BUCKET);
    }                                       

    private void bEraserActionPerformed(java.awt.event.ActionEvent evt) {                                        
       setDrawMode(DrawMode.ERASER);
    }                                       

    private void bPickerActionPerformed(java.awt.event.ActionEvent evt) {                                        
        setDrawMode(DrawMode.PICKER);
    }                                       
                                                                    
    private void bTriangleActionPerformed(java.awt.event.ActionEvent evt) {                                          
       setDrawMode(DrawMode.TRIANGLE);
    }                                         

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {                                       
        setDrawMode(DrawMode.SELECT);
    }                                      


    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton bBucket;
    private javax.swing.JToggleButton bCurve;
    private javax.swing.JToggleButton bEraser;
    private javax.swing.JToggleButton bFont;
    private javax.swing.JToggleButton bLine;
    private javax.swing.JToggleButton bOval;
    private javax.swing.JToggleButton bPencil;
    private javax.swing.JToggleButton bPicker;
    private javax.swing.JToggleButton bRectangle;
    private javax.swing.JToggleButton bTriangle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton select;
    // End of variables declaration                   
}
